apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sre-demo
  template:
    metadata:
      labels:
        app: sre-demo
    spec:
      containers:
      - name: sre-demo
        image: 641017921846.dkr.ecr.ap-south-1.amazonaws.com/testeks:latest
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000