# Use lightweight Node image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy files
COPY package.json .
RUN npm install

COPY app.js .

# Expose port
EXPOSE 3000

# Start app
CMD ["node", "app.js"]